# Generated by Django 2.1.7 on 2019-09-13 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=None, max_length=128, null=True)),
                ('place_snapshot', models.TextField(default=None, null=True)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('guests', models.PositiveIntegerField(default=1)),
                ('status', models.PositiveIntegerField(default=1)),
                ('reason', models.CharField(default=None, max_length=512, null=True)),
                ('wc_message', models.CharField(default=None, max_length=512, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
