# Generated by Django 2.1.7 on 2019-09-21 14:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20190914_0350'),
        ('reservations', '0002_auto_20190914_0350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('place', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_place', to='places.Place')),
                ('reservation', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_invoice', to='reservations.Reservation')),
            ],
        ),
    ]
