# Generated by Django 2.1.7 on 2019-09-22 21:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_paymentrequest'),
        ('reservations', '0003_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(default=0, null=True)),
                ('original_start', models.DateField(default=None, null=True)),
                ('original_end', models.DateField(default=None, null=True)),
                ('start', models.DateField(default=None, null=True)),
                ('end', models.DateField(default=None, null=True)),
                ('status', models.PositiveIntegerField(default=0, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('invoice', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='res_adjustment_invoice', to='transactions.Invoice')),
                ('reservation', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_res', to='reservations.Reservation')),
            ],
        ),
    ]
