# Generated by Django 2.1.7 on 2019-09-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_adjustments'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustments',
            name='reference',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
