# Generated by Django 2.1.7 on 2019-09-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_adjustments_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustments',
            name='guests',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='adjustments',
            name='original_guests',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
