# Generated by Django 2.1.7 on 2019-09-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20190926_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustments',
            name='ttype',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
