# Generated by Django 2.1.11 on 2019-11-09 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_adjustments_ttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='place',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_place', to='places.Place'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='reservation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_invoice', to='reservations.Reservation'),
        ),
    ]
