# Generated by Django 2.1.7 on 2019-09-13 21:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import places.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, null=True)),
                ('description', models.CharField(default='', max_length=256, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, null=True)),
                ('code', models.CharField(default='', max_length=128, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=places.models.place_image_path)),
                ('filename', models.CharField(default='', max_length=512, null=True)),
                ('title', models.CharField(default='', max_length=256, null=True)),
                ('description', models.CharField(default='', max_length=512, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('cover', models.BooleanField(default=False)),
                ('size', models.IntegerField(default=0)),
                ('type', models.CharField(blank=True, default=None, max_length=12, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256, null=True)),
                ('description', models.CharField(default='', max_length=2048, null=True)),
                ('code', models.CharField(default='', max_length=128, null=True)),
                ('max_guest', models.PositiveIntegerField(default=1)),
                ('address_one', models.CharField(default='', max_length=512, null=True)),
                ('address_two', models.CharField(default='', max_length=512, null=True)),
                ('state', models.CharField(default='', max_length=512, null=True)),
                ('zip', models.PositiveIntegerField(default=None, null=True)),
                ('beds', models.PositiveIntegerField(default=0)),
                ('baths', models.PositiveIntegerField(default=0)),
                ('checkin_from', models.PositiveIntegerField(default=0)),
                ('checkin_to', models.PositiveIntegerField(default=0)),
                ('checkout', models.PositiveIntegerField(default=0)),
                ('min_stay', models.PositiveIntegerField(default=1)),
                ('max_stay', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewid', models.CharField(default=None, max_length=28, null=True)),
                ('rating', models.FloatField(default=0)),
                ('review', models.CharField(default=None, max_length=2048, null=True)),
                ('type', models.PositiveIntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, null=True)),
                ('description', models.CharField(default='', max_length=256, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, null=True)),
                ('description', models.TextField(default='', null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, null=True)),
                ('code', models.CharField(default='', max_length=128, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.City')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, null=True)),
                ('description', models.TextField(default='', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
