# Generated by Django 2.1.7 on 2019-09-13 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0002_review_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='place',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='places.Amenity'),
        ),
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.City'),
        ),
        migrations.AddField(
            model_name='place',
            name='host',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='place',
            name='reviews',
            field=models.ManyToManyField(related_name='all_reviews', to='places.Review'),
        ),
        migrations.AddField(
            model_name='place',
            name='rules',
            field=models.ManyToManyField(blank=True, to='places.Rule'),
        ),
        migrations.AddField(
            model_name='place',
            name='space',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.Space'),
        ),
        migrations.AddField(
            model_name='place',
            name='type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.Type'),
        ),
        migrations.AddField(
            model_name='image',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place'),
        ),
    ]
