# Generated by Django 2.1.7 on 2019-09-16 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0002_auto_20190914_0350'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default=None, max_length=56, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('number', models.CharField(default=None, max_length=128, null=True)),
                ('status', models.CharField(default=None, max_length=56, null=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
