# Generated by Django 2.1.11 on 2019-11-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_paymentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(default=0, max_length=56, null=True),
        ),
    ]
