# Generated by Django 2.1.7 on 2019-09-13 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(default=None, max_length=28, null=True)),
                ('first_name', models.CharField(default='', max_length=128, null=True, verbose_name='first name')),
                ('last_name', models.CharField(default='', max_length=128, null=True, verbose_name='last name')),
                ('nickname', models.CharField(default='', max_length=256, null=True, verbose_name='nickname')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('mobile', models.CharField(max_length=24, unique=True, verbose_name='mobile')),
                ('photo', models.CharField(max_length=1024, verbose_name='photo')),
                ('dob', models.DateField(default=None, null=True)),
                ('gender', models.PositiveIntegerField(default=0)),
                ('credit', models.FloatField(default=0.0)),
                ('tsv', models.BooleanField(default=False)),
                ('address', models.CharField(default=None, max_length=512, null=True)),
                ('bio', models.CharField(default=None, max_length=1024, null=True)),
                ('password', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('email_code', models.CharField(blank=True, default='', max_length=24, null=True)),
                ('mobile_code', models.CharField(blank=True, default='', max_length=24, null=True)),
                ('reset_code', models.CharField(blank=True, default=None, max_length=24, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=1024, null=True)),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
