# Generated by Django 2.1.7 on 2019-09-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190918_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='method',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
