# Generated by Django 2.1.7 on 2019-09-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_documents_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
