# Generated by Django 2.1.7 on 2019-09-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190930_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='notes',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
